### ISSUE TITLE
Passar todo o repositório para o inglês

### ISSUE THREAD

**Issue by alaxalves** [fga-gpp-mds/2017.2-Grupo8#222]
Essa issue deverá ser dividida em _tasks_.

## Comportamento esperado

Todo o repositório deve estar em ingles.

## *Comportamento atual

Parte ingles parte em portugues.

## Checklist

- [x] A issue possui Labels.
- [ ] A issue possui prints de tela quando necessário.
- [x] A issue possui nome significativo.

**Comment by alaxalves** [comment]
Duplicada https://github.com/falko-org/Falko-API/issues/208
